name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for letting me know about the issue. If you know how to solve it, please open a pull request. We will work together.'
        pr-message: 'Thanks for contributing. You are always welcome whether it's about fixing a bug or adding a new feature.
