name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for letting me know about this issue. If you know how to fix this, you can make a pull request. We will work together.'
        pr-message: 'Thanks for contributing. You are always welcome whether it's fixing a bug or adding a new feature.'
